"""Add approved field to Writer

Revision ID: 054dde462da5
Revises: ff9bbe390159
Create Date: 2025-07-01 19:44:05.235453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '054dde462da5'
down_revision = 'ff9bbe390159'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('writer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('writer', schema=None) as batch_op:
        batch_op.drop_column('approved')

    # ### end Alembic commands ###
