"""Update Message model and other schema changes

Revision ID: 793aa7f31122
Revises: f471fb795e41
Create Date: 2025-07-25 17:36:46.052371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '793aa7f31122'
down_revision = 'f471fb795e41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=100), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=128), nullable=False))
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('announcement', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
