"""Add user_id to Order

Revision ID: 7bc4ae26edb5
Revises: eea8d623561f
Create Date: 2025-07-23 16:39:40.883502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bc4ae26edb5'
down_revision = 'eea8d623561f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   with op.batch_alter_table('order', schema=None) as batch_op:
    batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
    batch_op.create_foreign_key(
        'fk_order_user_id',  # Add a name for the constraint
        'user',
        ['user_id'],
        ['id']
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
