"""Add created_at to Writer

Revision ID: ff9bbe390159
Revises: 5c963ed62555
Create Date: 2025-07-01 19:33:13.116669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff9bbe390159'
down_revision = '5c963ed62555'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('writer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('subject',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.drop_column('orders')
        batch_op.drop_column('rating')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('writer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('orders', sa.INTEGER(), nullable=False))
        batch_op.alter_column('subject',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
